pages:
  stage: deploy
  image: alpine:latest
  script:
    - /bin/true
  artifacts:
    paths:
      - public
  environment:
    name: staging
    url: https://gitlab.com/madhead/awesome-opensearch
  only:
    - master

gh-pages:
  stage: deploy
  image:
    name: madhead/git:latest
    entrypoint: [""]
  before_script:
    - git config --global user.name  'GitLab'
    - git config --global user.email '<>'
    - mkdir ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - cd public
    - git init
    - git checkout -b gh-pages
    - git remote add origin git@github.com:madhead/awesome-opensearch.git
    - git add .
    - git commit --allow-empty-message --message ''
    - git push origin gh-pages -f
    - ssh-agent -k
  environment:
    name: production
    url: https://github.com/madhead/awesome-opensearch
  only:
    - master
